name=input("enter your name")
print(name)
age=input("enter your age")
print(age)
surname=input("enter your surname")
print(surname)
color=input("enter color")
print(color)
num1=input("enter your num1")
print(num1)